plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets.main.java.srcDirs = ["src/"]
sourceSets.main.resources.srcDirs = ["assets/"]

eclipse.project.name = appName + "-core"

sourceSets {
    main {
        java {
            srcDirs = ["src/"]
            exclude "test/**"
        }
        resources {
            srcDirs = ["assets/"]
        }
    }
    test {
        java {
            srcDirs = ["src/test/java"]
        }
    }
}

dependencies {
    api "com.badlogicgames.gdx:gdx:$gdxVersion"
    testImplementation "org.junit.jupiter:junit-jupiter:5.11.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.11.2"
}

test {
    useJUnitPlatform()
}
